
const ICONS={dashboard:'<path d="M4 4h6v6H4zM14 4h6v6h-6zM4 14h6v6H4zM14 14h6v6h-6z"/>',receipt:'<path d="M6 3h12v18l-3-2-3 2-3-2-3 2z"/><path d="M9 8h6M9 12h6"/>',chart:'<path d="M4 19V5M4 19h16"/><path d="m7 15 3-4 3 2 5-7"/>',wallet:'<path d="M4 7h15a2 2 0 0 1 2 2v9H5a2 2 0 0 1-2-2V6a3 3 0 0 1 3-3h12v4"/><path d="M17 13h4"/>',calendar:'<rect x="4" y="5" width="16" height="15" rx="2"/><path d="M8 3v4M16 3v4M4 10h16"/>',trend:'<path d="M4 18 10 12l4 4 6-9"/><path d="M15 7h5v5"/>',landmark:'<path d="m3 9 9-5 9 5M5 10v8M9 10v8M15 10v8M19 10v8M3 20h18"/>',target:'<circle cx="12" cy="12" r="8"/><circle cx="12" cy="12" r="4"/><circle cx="12" cy="12" r="1"/>',card:'<rect x="3" y="5" width="18" height="14" rx="2"/><path d="M3 10h18"/>',spark:'<path d="m12 3 1.6 5.4L19 10l-5.4 1.6L12 17l-1.6-5.4L5 10l5.4-1.6z"/>',search:'<circle cx="11" cy="11" r="6"/><path d="m16 16 5 5"/>',plus:'<path d="M12 5v14M5 12h14"/>',arrow:'<path d="M5 12h13M13 6l6 6-6 6"/>',shield:'<path d="M12 3 19 6v5c0 5-3 8-7 10-4-2-7-5-7-10V6z"/><path d="m9 12 2 2 4-4"/>',menu:'<path d="M4 7h16M4 12h16M4 17h16"/>',close:'<path d="M6 6l12 12M18 6 6 18"/>',settings:'<circle cx="12" cy="12" r="3"/><path d="M19.4 15a1.7 1.7 0 0 0 .3 1.9l.1.1-1.8 1.8-.1-.1a1.7 1.7 0 0 0-1.9-.3 1.7 1.7 0 0 0-1 1.6v.2h-2.5V20a1.7 1.7 0 0 0-1-1.6 1.7 1.7 0 0 0-1.9.3l-.1.1-1.8-1.8.1-.1a1.7 1.7 0 0 0 .3-1.9 1.7 1.7 0 0 0-1.6-1H6v-2.5h.2a1.7 1.7 0 0 0 1.6-1 1.7 1.7 0 0 0-.3-1.9l-.1-.1 1.8-1.8.1.1a1.7 1.7 0 0 0 1.9.3 1.7 1.7 0 0 0 1-1.6V5h2.5v.2a1.7 1.7 0 0 0 1 1.6 1.7 1.7 0 0 0 1.9-.3l.1-.1 1.8 1.8-.1.1a1.7 1.7 0 0 0-.3 1.9 1.7 1.7 0 0 0 1.6 1h.2v2.5h-.2a1.7 1.7 0 0 0-1.7 1.3z"/>',upload:'<path d="M12 16V4M8 8l4-4 4 4"/><path d="M4 15v4h16v-4"/>'};
const SUPABASE_URL='https://aoupsryzexkauzwccnpi.supabase.co'; const SUPABASE_KEY='sb_publishable_iOQkkrS_gCKcslz1tsms4g_7xvdAbdl'; const sb=window.supabase?.createClient(SUPABASE_URL,SUPABASE_KEY,{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:true}});
const I=n=>`<span class="ico"><svg viewBox="0 0 24 24">${ICONS[n]||ICONS.spark}</svg></span>`;
const nav=[['Overview','dashboard'],['Transactions','receipt'],['History','calendar'],['Cash Flow','chart'],['Budgets','wallet'],['Future','calendar'],['Investments','trend'],['Net Worth','landmark'],['Goals','target'],['Bills','card'],['Analytics','chart'],['Categories','target'],['Copilot','spark']];
const uid=()=>crypto.randomUUID(); const today=()=>new Date().toISOString().slice(0,10); const thisMonth=()=>today().slice(0,7); const money=n=>Number(n||0).toLocaleString('en-IN',{maximumFractionDigits:0}); const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const monthLabel=m=>new Date(`${m}-01T00:00:00`).toLocaleDateString('en-IN',{month:'long',year:'numeric'});
let page='Overview',authMode='login',mobile=false,modalState=null,selectedMonth=thisMonth();
let state={categories:[],subcategories:[],expenses:[],income:[],plans:[],investments:[],investmentContributions:[],recurring:[],bills:[],goals:[],goalContributions:[],assets:[],liabilities:[],subscriptions:[],monthlyBudgets:[],yearlyBudgets:[],baseIncome:{},members:[],settings:{}};
function toast(msg){let x=document.createElement('div');x.className='toast';x.textContent=msg;document.body.appendChild(x);setTimeout(()=>x.remove(),2800)}
function download(blob,name){const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1200)}
function modal(title,body,onSave,saveText='Save'){modalState={onSave};document.body.insertAdjacentHTML('beforeend',`<div class="modal-bg" id="modalBg"><div class="modal"><div class="modal-head"><div><div class="eyebrow">The Ledger</div><h2>${esc(title)}</h2></div><button class="close" id="modalClose">${I('close')}</button></div>${body}<div class="modal-actions"><button class="secondary" id="modalCancel">Cancel</button><button class="primary" id="modalSave">${saveText}</button></div></div></div>`);document.getElementById('modalClose').onclick=closeModal;document.getElementById('modalCancel').onclick=closeModal;document.getElementById('modalSave').onclick=async()=>{try{await onSave()}catch(e){toast(e.message||'Something went wrong')}}}
function closeModal(){document.getElementById('modalBg')?.remove();modalState=null}
function field(label,id,value='',type='text',extra=''){return `<div class="field"><label>${esc(label)}</label><input id="${id}" type="${type}" value="${esc(value)}" ${extra}></div>`}
function selectField(label,id,options,value=''){return `<div class="field"><label>${esc(label)}</label><select id="${id}"><option value="">Select…</option>${options.map(o=>`<option value="${esc(o.value)}" ${o.value===value?'selected':''}>${esc(o.label)}</option>`).join('')}</select></div>`}
function authView(){return `<div class="auth-screen"><div class="auth-card"><div class="mark big">L</div><div class="eyebrow">Private financial OS</div><h1>The Ledger</h1><p>One secure household. Every rupee. Every device. No financial data is preloaded.</p><div class="auth-tabs"><button class="auth-tab ${authMode==='login'?'active':''}" data-auth="login">Sign in</button><button class="auth-tab ${authMode==='signup'?'active':''}" data-auth="signup">Create account</button></div>${field('Email','authEmail','','email','autocomplete="email" placeholder="you@example.com"')}${field('Password','authPassword','','password','autocomplete="current-password" placeholder="••••••••"')}<button class="primary wide" id="authSubmit">${authMode==='login'?'Sign in':'Create account'}</button><div class="auth-status" id="authStatus"></div><div class="auth-foot">Cloud sync is on · encrypted in transit · row-level access control</div></div></div>`}
function renderAuth(){document.getElementById('app').innerHTML=authView();document.querySelectorAll('[data-auth]').forEach(b=>b.onclick=()=>{authMode=b.dataset.auth;renderAuth()});document.getElementById('authSubmit').onclick=authSubmit;setupAuthEnter()}
async function authSubmit(){const email=document.getElementById('authEmail').value.trim(),password=document.getElementById('authPassword').value;const s=document.getElementById('authStatus');if(!email||password.length<8){s.textContent='Enter a valid email and a password of at least 8 characters.';return}s.textContent='Working…';let r=authMode==='login'?await sb.auth.signInWithPassword({email,password}):await sb.auth.signUp({email,password,options:{emailRedirectTo:location.href}});if(r.error){s.textContent=r.error.message;return}if(authMode==='signup'&&!r.data.session){s.textContent='Account created. Check your email to confirm it, then sign in.'}else if(r.data.session) await bootCloud(r.data.session.user)}
function setupAuthEnter(){['authEmail','authPassword'].forEach(id=>document.getElementById(id)?.addEventListener('keydown',e=>{if(e.key==='Enter'){e.preventDefault();document.getElementById('authSubmit')?.click()}}))}
async function loadCloudContext(){const r=await sb.from('household_members').select('household_id,role').eq('user_id',cloud.user.id).maybeSingle();if(r.error)throw r.error;if(!r.data){cloud.member=null;cloud.household=null;return}cloud.member=r.data;const h=await sb.from('households').select('*').eq('id',r.data.household_id).single();if(h.error)throw h.error;cloud.household=h.data}
function onboarding(){document.getElementById('app').innerHTML=`<div class="auth-screen"><div class="auth-card"><div class="mark big">L</div><div class="eyebrow">Welcome to The Ledger</div><h1>Your household, your rules.</h1><p>Create a shared household or join an existing one with its invite code. The database starts completely empty.</p>${field('Your name','obName','','text','placeholder="Your name"')}${field('Household name','obHouse','','text','placeholder="Our Household"')}<button class="primary wide" id="createHouse">Create household</button><div class="divider">or join an existing household</div>${field('Invite code','obCode','','text','placeholder="AB12CD34EF"')}<button class="secondary wide" id="joinHouse">Join household</button><div class="auth-status" id="obStatus"></div></div></div>`;document.getElementById('createHouse').onclick=async()=>{await onboard('create')};document.getElementById('joinHouse').onclick=async()=>{await onboard('join')}}
async function onboard(mode){const status=document.getElementById('obStatus');status.textContent='Setting up…';try{const name=document.getElementById('obName').value.trim()||'User';let r;if(mode==='create')r=await sb.rpc('create_household',{p_name:document.getElementById('obHouse').value.trim()||'Our Household',p_display_name:name});else r=await sb.rpc('join_household',{p_invite_code:document.getElementById('obCode').value.trim(),p_display_name:name});if(r.error)throw r.error;await loadCloudContext();await loadCloudData();await materializeRecurring();await loadCloudData();cloud.ready=true;subscribeRealtime();render();toast(mode==='create'?'Household created':'Joined household')}catch(e){status.textContent=e.message||'Could not complete onboarding'}}
async function q(table,extra=''){let r=await sb.from(table).select('*').eq('household_id',cloud.household.id).order('created_at',{ascending:false});if(r.error)throw r.error;return r.data||[]}
async function loadCloudData(){if(!cloud.household)return;const [cats,subs,exps,inc,plans,inv,ic,rec,cc,goals,gc,assets,liab,subscrip,mb,yb,settings,members]=await Promise.all([q('categories'),q('subcategories'),q('expenses'),q('other_income'),q('plans'),q('investments'),q('investment_contributions'),q('recurring_items'),q('credit_card_bills'),q('goals'),q('goal_contributions'),q('assets'),q('liabilities'),q('subscriptions'),q('monthly_budgets'),q('yearly_budgets'),q('settings'),sb.from('household_members').select('user_id,role,profiles(display_name)').eq('household_id',cloud.household.id).then(x=>x.error?Promise.reject(x.error):x.data||[])]);state.categories=cats;state.subcategories=subs;state.expenses=exps;state.income=inc;state.plans=plans;state.investments=inv;state.investmentContributions=ic;state.recurring=rec;state.bills=cc;state.goals=goals;state.goalContributions=gc;state.assets=assets;state.liabilities=liab;state.subscriptions=subscrip;state.monthlyBudgets=mb;state.yearlyBudgets=yb;state.settings=settings[0]||{};state.baseIncome=state.settings.base_income||{};state.members=members;}
async function materializeRecurring(){const m=thisMonth();for(const r of state.recurring.filter(x=>x.auto_add)){const exists=state.expenses.some(e=>e.recurring_id===r.id&&e.expense_date?.startsWith(m));if(exists)continue;const day=String(Math.min(28,Math.max(1,Number(r.day||1)))).padStart(2,'0');const cat=state.categories.find(c=>c.id===r.category_id);if(!cat)continue;const rr=await sb.from('expenses').insert({id:uid(),household_id:cloud.household.id,category_id:r.category_id,subcategory_id:null,amount:r.amount,expense_date:`${m}-${day}`,note:r.label,added_by_name:'Auto',payment_method:r.payment_method||'',recurring_id:r.id,created_by:cloud.user.id});if(rr.error)throw rr.error}}
function subscribeRealtime(){if(!cloud.household)return;sb.removeAllChannels();['categories','subcategories','monthly_budgets','yearly_budgets','expenses','other_income','plans','investments','investment_contributions','recurring_items','credit_card_bills','goals','goal_contributions','assets','liabilities','subscriptions'].forEach(t=>sb.channel('ledger-'+t).on('postgres_changes',{event:'*',schema:'public',table:t,filter:'household_id=eq.'+cloud.household.id},async()=>{try{await loadCloudData();render()}catch(e){console.error(e)}}).subscribe())}
async function upsert(table,row){const r=await sb.from(table).upsert(row);if(r.error)throw r.error;await loadCloudData();render()}
async function remove(table,id){if(!confirm('Delete this item? This cannot be undone.'))return;const r=await sb.from(table).delete().eq('id',id).eq('household_id',cloud.household.id);if(r.error)throw r.error;await loadCloudData();render();toast('Deleted')}
function render(){if(!cloud.ready){renderAuth();return}document.getElementById('app').innerHTML=`<aside class="sidebar ${mobile?'open':''}"><div class="brand"><div class="mark">L</div><div><div class="brand-title">The Ledger</div><div class="brand-sub">Financial OS</div></div></div><div class="house"><span class="dot"></span>${esc(cloud.household.name)} · ${esc(activeName())}</div><nav class="nav">${nav.map(([n,ic])=>`<button class="${page===n?'active':''}" data-page="${n}">${I(ic)}<span>${n}</span>${n==='Copilot'?'<span class="badge">AI</span>':''}</button>`).join('')}</nav><div class="side-bottom"><nav class="nav"><button class="${page==='Settings'?'active':''}" data-page="Settings">${I('settings')}<span>Settings</span></button></nav><div class="privacy">${I('shield')} Private by design</div></div></aside><main class="main"><header class="topbar"><button class="menu" id="menu">${I('menu')}</button><div class="crumb"><span>Household</span>${I('arrow')}<strong>${page}</strong></div><div class="actions"><button class="search" id="search">${I('search')} Search <kbd>⌘ K</kbd></button><button class="ask" id="ask">${I('spark')} Ask Ledger</button><button class="avatar">${esc((activeName()||'L')[0].toUpperCase())}</button></div></header><section class="content">${pageView()}</section></main>`;wirePage()}
function activeName(){return state.members.find(m=>m.user_id===cloud.user.id)?.profiles?.display_name||'You'}
function pageView(){switch(page){case'History':return historyPage();case'Transactions':return transactions();case'Cash Flow':return cashflow();case'Budgets':return budgets();case'Future':return future();case'Investments':return investments();case'Net Worth':return networth();case'Goals':return goals();case'Bills':return bills();case'Analytics':return analytics();case'Categories':return categoriesPage();case'Copilot':return copilot();case'Settings':return settings();default:return overview()}}
function sum(a,fn){return a.reduce((s,x)=>s+Number(fn(x)||0),0)}
function overview(){
  const months=overviewMonths();
  const filtered=overviewFilteredExpenses();
  const income=overviewFilteredIncome();
  const spend=sum(filtered,x=>x.amount), inc=sum(income,x=>x.amount), net=inc-spend;
  const budget=overviewBudgetTotal();
  const recurring=sum(state.recurring.filter(x=>x.active!==false),x=>x.amount);
  const upcomingBills=sum(state.bills.filter(x=>!x.paid),x=>x.amount);
  const planned=state.plans.filter(x=>x.target_month>=thisMonth());
  const assets=sum(state.assets,x=>x.current_value)+sum(state.investments,x=>x.starting_value)+sum(state.investmentContributions,x=>x.amount);
  const liab=sum(state.liabilities,x=>x.balance), nw=assets-liab;
  const savings=inc?Math.max(0,net)/inc*100:0;
  const remaining=budget-spend;
  return `<div class="hero"><div><div class="eyebrow">Financial command center · ${overviewScopeLabel()}</div><h1>See where your money is going.</h1><p>Explore spending, cash flow, budgets, commitments, plans and wealth from one place. Every chart responds to the filters below.</p></div><button class="primary" id="addExpense">${I('plus')} Add transaction</button></div>
  <section class="card overview-filters"><div class="panel-head"><div><h2>Explore your finances</h2><div class="panel-desc">Filter the dashboard, then change the analysis dimension.</div></div><button class="secondary" id="resetOverviewFilters">Reset</button></div>
  <div class="filter-grid">
    ${selectField('View','ovScope',[{value:'month',label:'Selected month'},{value:'range',label:'Date range'},{value:'year',label:'Selected year'},{value:'all',label:'All available data'}],ovFilters.scope)}
    ${selectField('Month','ovMonth',availableMonthOptions(),ovFilters.month)}
    ${selectField('Year','ovYear',overviewYears(),ovFilters.year)}
    ${ovFilters.scope==='range'?field('From','ovFrom',ovFilters.from,'date'):''}
    ${ovFilters.scope==='range'?field('To','ovTo',ovFilters.to,'date'):''}
    ${selectField('Category','ovCategory',[{value:'',label:'All categories'},...state.categories.map(x=>({value:x.id,label:x.name}))],ovFilters.category)}
    ${selectField('Subcategory','ovSubcategory',[{value:'',label:'All subcategories'},...state.subcategories.filter(x=>!ovFilters.category||x.category_id===ovFilters.category).map(x=>({value:x.id,label:x.name}))],ovFilters.subcategory)}
    ${selectField('Person','ovPerson',[{value:'',label:'Everyone'},...state.members.map(x=>({value:x.profiles?.display_name||x.display_name||x.user_id,label:x.profiles?.display_name||x.display_name||'Member'}))],ovFilters.person)}
    ${selectField('Payment','ovPayment',[{value:'',label:'All methods'},...['UPI','Cash','Card','Credit Card','Bank Transfer','Other'].map(x=>({value:x,label:x}))],ovFilters.payment)}
    ${selectField('Plan','ovPlan',[{value:'',label:'All plans'},...state.plans.map(x=>({value:x.id,label:x.name||x.title||'Plan'}))],ovFilters.plan)}
  </div></section>
  <div class="stat-grid">
    ${metricCard('Income',`₹${money(inc)}`,`${income.length} income entries`,'chart')}
    ${metricCard('Spending',`₹${money(spend)}`,`${filtered.length} expense entries`,'receipt')}
    ${metricCard('Net cash flow',`₹${money(net)}`,net>=0?'positive':'negative','trend')}
    ${metricCard('Budget remaining',`₹${money(remaining)}`,budget?`${Math.round(spend/budget*100)}% used`:'No budget set','wallet')}
    ${metricCard('Savings rate',`${savings.toFixed(1)}%`,inc?'income less spending':'Add income','target')}
    ${metricCard('Net worth',`₹${money(nw)}`,'assets minus liabilities','landmark')}
    ${metricCard('Recurring',`₹${money(recurring)}`,'active recurring commitments','calendar')}
    ${metricCard('Upcoming bills',`₹${money(upcomingBills)}`,`${state.bills.filter(x=>!x.paid).length} unpaid bills`,'card')}
  </div>
  <div class="analytics-grid two"><section class="card panel"><div class="panel-head"><div><h2>Spending trend</h2><div class="panel-desc">${months.length} periods · filtered expense data</div></div>${chartDimensionSelect()}</div>${overviewTrendChart(months)}</section><section class="card panel"><div class="panel-head"><div><h2>Income vs expense</h2><div class="panel-desc">Cash-flow movement over time</div></div></div>${incomeExpenseChart(months)}</section></div>
  <div class="analytics-grid three"><section class="card panel"><div class="panel-head"><div><h2>Spending mix</h2><div class="panel-desc">Part of the selected spend</div></div></div>${overviewPie()}</section><section class="card panel"><div class="panel-head"><div><h2>Top ${dimensionLabel(ovFilters.dimension)}</h2><div class="panel-desc">Ranked spending</div></div></div>${overviewBar()}</section><section class="card panel"><div class="panel-head"><div><h2>Budget vs actual</h2><div class="panel-desc">Category control</div></div></div>${budgetActualChart()}</section></div>
  <div class="analytics-grid two"><section class="card panel"><div class="panel-head"><div><h2>Category trend</h2><div class="panel-desc">Select a category or compare the leaders</div></div>${trendCategorySelect()}</div>${categoryTrendChart(months)}</section><section class="card panel"><div class="panel-head"><div><h2>Subcategory trend</h2><div class="panel-desc">Drill into the selected category</div></div></div>${subcategoryTrendChart(months)}</section></div>
  <div class="analytics-grid three"><section class="card panel compact"><div class="panel-head"><div><h2>Who spent what</h2><div class="panel-desc">Household attribution</div></div></div>${personChart()}</section><section class="card panel compact"><div class="panel-head"><div><h2>Payment methods</h2><div class="panel-desc">Where spending was paid</div></div></div>${paymentChart()}</section><section class="card panel compact"><div class="panel-head"><div><h2>Plans & goals</h2><div class="panel-desc">Future commitments</div></div></div>${planGoalMini()}</section></div>
  <div class="analytics-grid two"><section class="card panel"><div class="panel-head"><div><h2>Monthly budget planner</h2><div class="panel-desc">A transparent starting point from your spending history.</div></div></div>${budgetPlanner()}</section><section class="card panel"><div class="panel-head"><div><h2>Financial signals</h2><div class="panel-desc">Useful indicators, not financial advice.</div></div></div>${financialSignals()}</section></div>`;
}
