
let ovFilters={scope:'month',month:thisMonth(),year:new Date().getFullYear().toString(),from:new Date(new Date().setDate(new Date().getDate()-30)).toISOString().slice(0,10),to:today(),category:'',subcategory:'',person:'',payment:'',plan:'',dimension:'category',trendCategory:''};
function availableMonthOptions(){const set=new Set([thisMonth(),...state.expenses.map(x=>x.expense_date?.slice(0,7)).filter(Boolean),...state.income.map(x=>x.income_date?.slice(0,7)).filter(Boolean),...state.monthlyBudgets.map(x=>x.month).filter(Boolean)]);return [...set].sort().reverse().map(m=>({value:m,label:monthLabel(m)}))}
function overviewYears(){const ys=new Set([String(new Date().getFullYear()),...state.expenses.map(x=>x.expense_date?.slice(0,4)).filter(Boolean),...state.income.map(x=>x.income_date?.slice(0,4)).filter(Boolean)]);return [...ys].sort().reverse().map(y=>({value:y,label:y}))}
function overviewScopeLabel(){return ovFilters.scope==='month'?monthLabel(ovFilters.month):ovFilters.scope==='year'?`Year ${ovFilters.year}`:ovFilters.scope==='range'?'Filtered range':'All available history'}
function overviewDateMatch(date){if(!date)return false;if(ovFilters.scope==='all')return true;if(ovFilters.scope==='month')return date.startsWith(ovFilters.month);if(ovFilters.scope==='year')return date.startsWith(ovFilters.year);if(ovFilters.scope==='range')return date>=ovFilters.from&&date<=ovFilters.to;return true}
function overviewFilteredExpenses(){return state.expenses.filter(x=>overviewDateMatch(x.expense_date)&&(!ovFilters.category||x.category_id===ovFilters.category)&&(!ovFilters.subcategory||x.subcategory_id===ovFilters.subcategory)&&(!ovFilters.person||x.added_by===ovFilters.person||x.person_id===ovFilters.person||x.added_by_name===((state.members.find(m=>m.id===ovFilters.person)?.profiles?.display_name)||''))&&(!ovFilters.payment||x.payment_method===ovFilters.payment)&&(!ovFilters.plan||x.plan_id===ovFilters.plan))}
function overviewFilteredIncome(){return state.income.filter(x=>overviewDateMatch(x.income_date)&&(!ovFilters.person||x.person_id===ovFilters.person||x.added_by===ovFilters.person||x.received_by_name===ovFilters.person))}
function overviewMonths(){if(ovFilters.scope==='range'){const out=[],d=new Date(`${ovFilters.from}T00:00:00`),end=new Date(`${ovFilters.to}T00:00:00`);d.setDate(1);end.setDate(1);while(d<=end){out.push(d.toISOString().slice(0,7));d.setMonth(d.getMonth()+1)}return out.length?out:[thisMonth()]}const n=ovFilters.scope==='year'?12:ovFilters.scope==='all'?12:6;const end=ovFilters.scope==='month'?new Date(`${ovFilters.month}-01T00:00:00`):new Date();if(ovFilters.scope==='year')end.setMonth(11);const out=[];for(let i=n-1;i>=0;i--){const d=new Date(end);d.setMonth(end.getMonth()-i);out.push(d.toISOString().slice(0,7))}return out}
function overviewBucket(ex){const map={};ex.forEach(x=>{const k=x.category_id||'__uncat';map[k]=(map[k]||0)+Number(x.amount||0)});return Object.entries(map).sort((a,b)=>b[1]-a[1])}
function metricCard(label,value,sub,icon){return `<article class="card stat"><div class="stat-head"><span>${label}</span>${I(icon)}</div><div class="number">${value}</div><div class="sub">${sub}</div></article>`}
function chartDimensionSelect(){return selectField('Trend by','ovDimension',[{value:'total',label:'Total spending'},{value:'category',label:'Category'},{value:'subcategory',label:'Subcategory'},{value:'person',label:'Person'}],ovFilters.dimension)}
function dimensionLabel(d){return d==='subcategory'?'subcategories':d==='person'?'people':d==='payment'?'payment methods':'categories'}
function expenseLabel(x,dimension){if(dimension==='subcategory')return state.subcategories.find(s=>s.id===x)?.name||'Uncategorized';if(dimension==='person'){const m=state.members.find(m=>m.id===x);return m?.profiles?.display_name||m?.display_name||x||'Unknown';}if(dimension==='payment')return x||'Other';const c=state.categories.find(c=>c.id===x);return c?.name||'Uncategorized'}
function groupedExpenses(ex,dimension){const map={};ex.forEach(x=>{let key=dimension==='subcategory'?x.subcategory_id:dimension==='person'?(x.person_id||x.added_by||x.added_by_name):dimension==='payment'?x.payment_method:x.category_id;if(!key)key='__uncat';map[key]=(map[key]||0)+Number(x.amount||0)});return Object.entries(map).sort((a,b)=>b[1]-a[1])}
function overviewPie(){const rows=groupedExpenses(overviewFilteredExpenses(),ovFilters.dimension==='total'?'category':ovFilters.dimension).slice(0,6);if(!rows.length)return emptyAnalytics('No spending in this filter');const total=sum(rows,x=>x[1]);let acc=0;const r=52,cx=65,cy=65,circ=2*Math.PI*r;return `<div class="donut-wrap"><svg viewBox="0 0 130 130" class="donut">${rows.map(([k,v],i)=>{const len=v/total*circ,off=-acc;acc+=len;return `<circle cx="65" cy="65" r="52" fill="none" stroke="hsl(${i*55+155} 55% 55%)" stroke-width="22" stroke-dasharray="${len} ${circ-len}" stroke-dashoffset="${off}" transform="rotate(-90 65 65)"/>`}).join('')}<circle cx="65" cy="65" r="38" fill="var(--panel)"/><text x="65" y="62" text-anchor="middle" class="donut-total">₹${money(total)}</text><text x="65" y="75" text-anchor="middle" class="donut-label">selected spend</text></svg><div class="legend">${rows.map(([k,v],i)=>`<div><i style="background:hsl(${i*55+155} 55% 55%)"></i><span>${esc(expenseLabel(k,ovFilters.dimension==='total'?'category':ovFilters.dimension))}</span><b>${Math.round(v/total*100)}%</b></div>`).join('')}</div></div>`}
