function overviewBar(){const d=ovFilters.dimension==='total'?'category':ovFilters.dimension;const rows=groupedExpenses(overviewFilteredExpenses(),d).slice(0,8);if(!rows.length)return emptyAnalytics('No spending in this filter');const max=Math.max(...rows.map(x=>x[1]),1);return `<div class="rank-bars">${rows.map(([k,v])=>`<div class="rank-row"><div class="rank-label"><span>${esc(expenseLabel(k,d))}</span><b>₹${money(v)}</b></div><div class="rank-track"><i style="width:${v/max*100}%"></i></div></div>`).join('')}</div>`}
function overviewTrendChart(months){const ex=state.expenses.filter(x=>overviewDateMatch(x.expense_date)&&(!ovFilters.category||x.category_id===ovFilters.category)&&(!ovFilters.subcategory||x.subcategory_id===ovFilters.subcategory)&&(!ovFilters.person||x.person_id===ovFilters.person||x.added_by===ovFilters.person)&&(!ovFilters.payment||x.payment_method===ovFilters.payment)&&(!ovFilters.plan||x.plan_id===ovFilters.plan));const d=ovFilters.dimension;if(d==='total')return simpleLine(months,months.map(m=>sum(ex.filter(x=>x.expense_date?.startsWith(m)),x=>x.amount)),'₹');const groups=groupedExpenses(ex,d).slice(0,5);return multiLine(months,groups.map(([k])=>({name:expenseLabel(k,d),values:months.map(m=>sum(ex.filter(x=>x.expense_date?.startsWith(m)&&((d==='category'&&x.category_id===k)||(d==='subcategory'&&x.subcategory_id===k)||(d==='person'&&(x.person_id===k||x.added_by===k)))),x=>x.amount))})))}
function simpleLine(labels,values,prefix=''){if(!values.some(Boolean))return emptyAnalytics('No trend data');const max=Math.max(...values,1),pts=values.map((v,i)=>`${(i/(Math.max(labels.length-1,1)))*100},${100-(v/max*86)-7}`).join(' ');return `<div class="svg-chart"><svg viewBox="0 0 100 100" preserveAspectRatio="none"><path class="gridline" d="M0 20H100M0 50H100M0 80H100"/><polyline class="chart-line" points="${pts}"/></svg><div class="chart-axis">${labels.map(x=>`<span>${monthLabel(x).split(' ')[0]}</span>`).join('')}</div><div class="chart-value">${prefix}${money(Math.max(...values))} peak</div></div>`}
function multiLine(labels,series){if(!series.length)return emptyAnalytics('No trend data');const max=Math.max(...series.flatMap(s=>s.values),1);return `<div class="svg-chart"><svg viewBox="0 0 100 100" preserveAspectRatio="none">${series.map((s,j)=>`<polyline class="chart-line" style="stroke:hsl(${j*55+155} 55% 55%)" points="${s.values.map((v,i)=>`${i/(Math.max(labels.length-1,1))*100},${100-(v/max*86)-7}`).join(' ')}"/>`).join('')}</svg><div class="chart-axis">${labels.map(x=>`<span>${monthLabel(x).split(' ')[0]}</span>`).join('')}</div><div class="legend">${series.map((s,j)=>`<div><i style="background:hsl(${j*55+155} 55% 55%)"></i><span>${esc(s.name)}</span></div>`).join('')}</div></div>`}
function incomeExpenseChart(months){const inc=months.map(m=>sum(state.income.filter(x=>x.income_date?.startsWith(m)&&(!ovFilters.person||x.person_id===ovFilters.person||x.added_by===ovFilters.person)),x=>x.amount));const ex=months.map(m=>sum(state.expenses.filter(x=>x.expense_date?.startsWith(m)&&(!ovFilters.category||x.category_id===ovFilters.category)&&(!ovFilters.subcategory||x.subcategory_id===ovFilters.subcategory)&&(!ovFilters.person||x.person_id===ovFilters.person||x.added_by===ovFilters.person)&&(!ovFilters.payment||x.payment_method===ovFilters.payment)&&(!ovFilters.plan||x.plan_id===ovFilters.plan)),x=>x.amount));return multiLine(months,[{name:'Income',values:inc},{name:'Expense',values:ex}])}
function budgetActualChart(){const ex=overviewFilteredExpenses();const rows=state.categories.map(c=>{const actual=sum(ex.filter(x=>x.category_id===c.id),x=>x.amount);const b=sum(state.monthlyBudgets.filter(x=>x.month===ovFilters.month),x=>Number(x.category_budgets?.[c.id]||0));return [c.name,b,actual]}).filter(x=>x[1]||x[2]).sort((a,b)=>(b[2]-a[2])).slice(0,7);if(!rows.length)return emptyAnalytics('No budget or spending data');return `<div class="budget-bars">${rows.map(r=>`<div><div class="rank-label"><span>${esc(r[0])}</span><b>₹${money(r[2])} / ₹${money(r[1])}</b></div><div class="dual-track"><i style="width:${r[1]?Math.min(100,r[2]/r[1]*100):100}%"></i></div></div>`).join('')}</div>`}
function trendCategorySelect(){return selectField('Focus category','ovTrendCategory',[{value:'',label:'Top categories'},...state.categories.map(c=>({value:c.id,label:c.name}))],ovFilters.trendCategory)}
function categoryTrendChart(months){const ex=state.expenses;let cats=ovFilters.trendCategory?[ovFilters.trendCategory]:groupedExpenses(overviewFilteredExpenses(),'category').slice(0,5).map(x=>x[0]);return multiLine(months,cats.map(k=>({name:expenseLabel(k,'category'),values:months.map(m=>sum(ex.filter(x=>x.expense_date?.startsWith(m)&&x.category_id===k),x=>x.amount))})))}
function subcategoryTrendChart(months){const ex=state.expenses;const subs=groupedExpenses(overviewFilteredExpenses(),'subcategory').slice(0,5).map(x=>x[0]);return multiLine(months,subs.map(k=>({name:expenseLabel(k,'subcategory'),values:months.map(m=>sum(ex.filter(x=>x.expense_date?.startsWith(m)&&x.subcategory_id===k),x=>x.amount))})))}
function personChart(){const rows=groupedExpenses(overviewFilteredExpenses(),'person').slice(0,7);return rows.length?overviewRankMini(rows,'person'):emptyAnalytics('No person attribution yet')}
